module TauPoset
export enumerateTauTilts

@static if 1 < 0
    include("taurigids.jl")
end
using Oscar, ..TauRigids

coker(f::GAP.GapObj) = GAP.Globals.CoKernel(f)

directSum(smds::Vector{GAP.GapObj}) =
    GAP.Globals.DirectSumOfQPAModules(GapObj(smds))

minLeftApprox(x::GAP.GapObj, m::GAP.GapObj) =
    GAP.Globals.MinimalLeftApproximation(x, m)

function enumerateTauTilts(alg::GAP.GapObj; timeout::Int64=10)
    if GAP.Globals.Dimension(alg) == GAP.Globals.infinity
        throw(ArgumentError("Method only implemented for finite dimensional algebras! Hint: taking the quotient by an ideal generated by central elements in the radical does not change the τ-tilting poset, but may make the algebra finite dimensional."))
    end

    timer = run(`sh -c "sleep $(timeout) && kill -2 $(getpid())"`, wait=false)

    zeroModule = GAP.Globals.ZeroModule(alg)

    seed = GAP.Globals.IndecProjectiveModules(alg)
    maxElt = SuppTauTilting(Set(IndecTauRigid.(seed)))
    minElt = SuppTauTilting(Set(), algebra_rank=length(seed))

    result = Set([maxElt, minElt])

    try
        fromTop = [maxElt]
        while !isempty(fromTop)
            newFromTop = []

            for mx in fromTop

                # Check if mutation has already been computed. 
                # This is inexpensive and takes ~0.001s
                for my in result
                    mxy = setdiff(mx.summands, my.summands)
                    myx = setdiff(my.summands, mx.summands)

                    if length(mxy) == 1 && length(myx) == 1 &&
                       mx.complement == my.complement
                        x = first(mxy)
                        y = first(myx)
                        mx.mutations[x] = my.uid
                        my.mutations[y] = mx.uid
                    elseif length(mxy) == 1 && isempty(myx)
                        x = first(mxy)
                        y = first(setdiff(my.complement, mx.complement))
                        mx.mutations[x] = my.uid
                        my.mutations[y] = mx.uid
                    elseif length(myx) == 1 && isempty(mxy)
                        x = first(setdiff(mx.complement, my.complement))
                        y = first(myx)
                        mx.mutations[x] = my.uid
                        my.mutations[y] = mx.uid
                    else
                        continue
                    end
                end

                # Compute genuinely new modules: computational bottleneck
                for x in setdiff(mx.summands, keys(mx.mutations))

                    smds_of_m = setdiff(mx.summands, (x,))
                    m = isempty(smds_of_m) ? zeroModule :
                        directSum(getproperty.(smds_of_m, :obj))

                    f = minLeftApprox(x.obj, m)

                    y = IndecTauRigid(coker(f))

                    smds_of_m = iszero(y.dim) ? smds_of_m : push!(smds_of_m, y)
                    my = SuppTauTilting(smds_of_m)

                    y = iszero(y.dim) ?
                        first(setdiff(my.complement, mx.complement)) : y

                    mx.mutations[x] = my.uid
                    my.mutations[y] = mx.uid

                    push!(newFromTop, my)
                    push!(result, my)
                end
            end

            fromTop = newFromTop
        end

        kill(timer)
        return result

    catch err
        if err isa InterruptException
            @info "Computation interrupted, possibly because timeout was hit.\nReturning partial results..."
            kill(timer)
            return result
        else
            kill(timer)
            rethrow(err)
        end
    end
end

end
