module TauPoset
export enumerateTauTilts

@static if 1 < 0
    include("taurigids.jl")
end
using Oscar, ..TauRigids

function enumerateTauTilts(alg::GAP.GapObj; timeout::Real=90.0)
    if GAP.Globals.Dimension(alg) == GAP.Globals.infinity
        throw(ArgumentError("Method only implemented for finite dimensional algebras! Hint: taking the quotient by an ideal generated by central elements in the radical does not change the τ-tilting poset, but may make the algebra finite dimensional."))
    end

    seed = GAP.Globals.IndecProjectiveModules(alg)
    maxElt = SuppTauTilting(Set(IndecTauRigid.(seed)))
    minElt = SuppTauTilting(Set(), algebra_rank=length(seed))

    result = Set([maxElt, minElt])

    fromTop = [maxElt]

    start_time = time()
    while isnothing(timeout) || (time() - start_time) <= timeout

        if isempty(fromTop)
            break
        end

        newFromTop = []

        for mx in fromTop
            for my in result
                mxy = setdiff(mx.summands, my.summands)
                myx = setdiff(my.summands, mx.summands)

                if length(mxy) == 1 && length(myx) == 1
                    x = first(mxy)
                    y = first(myx)
                elseif length(mxy) == 1 && isempty(myx)
                    x = first(mxy)
                    y = first(setdiff(my.complement, mx.complement))
                elseif length(myx) == 1 && isempty(mxy)
                    x = first(setdiff(mx.complement, my.complement))
                    y = first(myx)
                else
                    continue
                end

                mx.mutations[x] = my.uid
                my.mutations[y] = mx.uid
            end

            for x in setdiff(mx.summands, keys(mx.mutations))
                smds_of_m = setdiff(mx.summands, (x,))
                m = isempty(smds_of_m) ?
                    GAP.Globals.ZeroModule(alg) :
                    GAP.Globals.DirectSumOfQPAModules(GapObj(collect(getproperty.(smds_of_m, :obj))))
                f = GAP.Globals.MinimalLeftApproximation(x.obj, m)
                y = IndecTauRigid(GAP.Globals.CoKernel(f))

                if !iszero(y.gvec)
                    push!(smds_of_m, y)
                end

                my = SuppTauTilting(smds_of_m)

                mx.mutations[x] = my.uid
                my.mutations[y] = mx.uid

                push!(newFromTop, my)
                push!(result, my)
            end
        end

        fromTop = newFromTop
    end

    return result
end

end
